### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [Roundaround/mc-fabric-pickup-notifications#30] opened 2024-05-18 08:23 UTC
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'pickupnotifications'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:484)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/networking/v1/ClientPlayNetworking$PlayChannelHandler
	at me.roundaround.pickupnotifications.network.ItemAddedPacket.registerReceive(ItemAddedPacket.java:19)
	at me.roundaround.pickupnotifications.PickupNotificationsMod.onInitializeClient(PickupNotificationsMod.java:23)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 9 more

**Comment by Roundaround** [comment] 2024-06-19 16:10
https://github.com/Roundaround/mc-fabric-roundalib/issues/1

**Comment by Roundaround** [comment] 2024-06-19 16:12
Duplicate of #31

**Comment by Roundaround** [comment] 2024-06-19 16:13
Duplicate of #31

**Closed by Roundaround** 2024-06-19 16:13 UTC

**Comment by sternschnaube** [comment] 2024-06-19 17:02
Thank you, take all the time please 😊
Congrats ❤️
